version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/front/vite-project"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - '*'
  - package-ecosystem: "pip"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - '*'
  - package-ecosystem: "pip"
    directory: "/src/batch"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'github-actions'
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - '*'