version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/front/vite-project"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src/backend"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src/batch"
    schedule:
      interval: "daily"